name: "Deployer Action"
description: "Call Deployer API to trigger deployment"
inputs:
  api_url:
    description: "Deployer API URL"
    required: true
  deploy_token:
    description: "Deployer Token for Authentication"
    required: true
  base_path:
    description: "Deployer Base Path"
    required: true
  scripts:
    description: "Deployment Scripts to Execute"
    required: true
runs:
  using: "node20"
  main: "index.js"
